title: Keith Brady's Portfolio of Projects
description: [Portfolio of my projects related to Cybersecurity and Data Analytics] 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
